worker_processes 1;

events {
  worker_connections 1024;
}

http {
  include       mime.types;
  sendfile      on;

  server {
    listen 80;

    # OHIF viewer
    location / {
      proxy_pass http://ohif:80/;
      proxy_set_header Host $host;
    }

    # DICOMweb (fondamentale)
    location /dicom-web/ {
      proxy_pass http://orthanc:8042/dicom-web/;
      proxy_set_header Host $host;
    }

    # WADO
    location /wado/ {
      proxy_pass http://orthanc:8042/wado/;
      proxy_set_header Host $host;
    }

    # Orthanc UI (debug)
    location /orthanc/ {
      proxy_pass http://orthanc:8042/;
      proxy_set_header Host $host;
    }
  }
}