worker_processes 1;

events {
  worker_connections 1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;

  client_max_body_size 2048m;
  proxy_request_buffering off;
  proxy_buffering off;

  server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 2048m;

    location /dicom-web/ {
      proxy_pass http://127.0.0.1:8042/dicom-web/;
      proxy_set_header Host $host;
    }

    location /wado/ {
      proxy_pass http://127.0.0.1:8042/wado/;
      proxy_set_header Host $host;
    }

    location /orthanc/ {
      client_max_body_size 2048m;
      proxy_pass http://127.0.0.1:8042/;
      proxy_set_header Host $host;
      proxy_request_buffering off;
      proxy_buffering off;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}